# Generated by Django 2.1.4 on 2019-12-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projectlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, unique=True, verbose_name='项目名称')),
                ('project_image', models.CharField(max_length=255, unique=True, verbose_name='项目立项镜像')),
                ('deploy_type', models.CharField(choices=[('deployment', '部署集'), ('statefulset', '有状态副本集')], help_text='deployment(无状态应用),statefulset(有状态应用)', max_length=64, verbose_name='项目立项类别')),
                ('project_replicas', models.CharField(max_length=64, verbose_name='副本数')),
                ('project_port', models.CharField(max_length=64, verbose_name='应用端口')),
                ('env_set', models.CharField(max_length=255, verbose_name='立项自定义环境变量')),
                ('imagepullsecrets', models.CharField(max_length=255, verbose_name='使用的imagepullsecrets')),
            ],
            options={
                'verbose_name': '立项列表',
                'verbose_name_plural': '立项列表',
            },
        ),
    ]
