# Generated by Django 2.1.4 on 2019-12-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0002_projectlist_project_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_namespace',
            field=models.CharField(max_length=255, verbose_name='项目组'),
        ),
    ]
