# Generated by Django 2.1.4 on 2019-12-03 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0004_auto_20191203_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_user',
            field=models.CharField(default='abc', max_length=255, verbose_name='项目创建人'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 14, 52, 46, 949051), verbose_name='项目创建时间'),
        ),
    ]
