# Generated by Django 2.1.4 on 2019-12-03 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0005_auto_20191203_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 14, 53, 13, 280709), verbose_name='项目创建时间'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_user',
            field=models.CharField(max_length=255, verbose_name='项目创建人'),
        ),
    ]
