# Generated by Django 2.1.4 on 2019-12-03 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0006_auto_20191203_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_status',
            field=models.CharField(default='create', max_length=255, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 15, 27, 5, 63777), verbose_name='项目创建时间'),
        ),
    ]
