# Generated by Django 2.1.4 on 2019-12-03 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0007_auto_20191203_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 16, 22, 2, 95860), verbose_name='项目创建时间'),
        ),
    ]
