# Generated by Django 2.1.4 on 2019-12-11 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0009_auto_20191210_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostPassTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_user', models.CharField(max_length=10, unique=True, verbose_name='主机用户')),
                ('host_pass', models.CharField(max_length=255, verbose_name='主机密码')),
                ('host_room', models.CharField(max_length=20, verbose_name='所在机房')),
            ],
            options={
                'verbose_name': '主机密码表',
                'verbose_name_plural': '主机密码表',
            },
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 13, 31, 42, 294256), verbose_name='项目创建时间'),
        ),
    ]
