# Generated by Django 2.1.4 on 2019-12-11 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0010_auto_20191211_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpasstable',
            name='host_room',
            field=models.CharField(max_length=20, unique=True, verbose_name='所在机房'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 13, 49, 6, 151572), verbose_name='项目创建时间'),
        ),
    ]
