# Generated by Django 2.1.4 on 2019-12-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0011_auto_20191211_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 16, 2, 5, 242746), verbose_name='项目创建时间'),
        ),
    ]
