# Generated by Django 2.1.4 on 2019-12-18 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0013_auto_20191211_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 13, 12, 41, 171101), verbose_name='项目创建时间'),
        ),
    ]
