# Generated by Django 2.1.4 on 2019-12-18 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0015_auto_20191218_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_create_id',
            field=models.CharField(default='xx', max_length=255, verbose_name='项目创建任务id'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='project_volumecreate_id',
            field=models.CharField(default='xx', max_length=255, verbose_name='项目存储创建任务id'),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 15, 8, 46, 411521), verbose_name='项目创建时间'),
        ),
    ]
