# Generated by Django 2.1.4 on 2019-12-19 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0017_auto_20191219_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 19, 16, 31, 29, 601197), verbose_name='项目创建时间'),
        ),
    ]
