# Generated by Django 2.1.4 on 2019-12-20 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0018_auto_20191219_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='project_createtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='项目创建时间'),
        ),
    ]
