# Generated by Django 2.1.4 on 2020-01-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubeitems', '0019_auto_20191220_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_svc_id',
            field=models.CharField(default='xx', max_length=255, verbose_name='项目服务网关创建任务id'),
        ),
    ]
