apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster
  namespace: ops
spec:
  #clusterIP: 10.66.18.195
  ports:
  - port: 49152
    protocol: TCP
    targetPort: 49152
  sessionAffinity: None
  type: ClusterIP
