# Generated by Django 2.1.4 on 2020-07-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kubeadmin', '0003_auto_20190906_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubepermission',
            name='k8sapi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kubeadmin.KubeEnv', to_field='k8s_ident', verbose_name='k8s集群'),
        ),
    ]
