XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX   XXXXXXXXXXXX
BBB BBBB BB BBBBBBBBB
    BB BBBB BB BBBBBBBBBBBB
        XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBB
        XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBB
BBBBBB