BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX X  X XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXX  XXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXXXXXXXXX
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB  BB BBBBBBBBBBBBBBBB
                                XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXX
                                XXXXXXXXX
                                XXX XXXXXXXXXXXXXXXXXXXXX
                                BBBBB

                            BBBBBB
                        XXXXX
                    XXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXXX
        XXX XXXXXXXXXXX X XXX
        XXX XXXXXXXXXXXXXX X XXX
        XXX XXXXXXX X XXX
        XXX XXXXXXXXXXXXXX X XXX
    XXXXXXXXX
XXXXXXX
XXXXXXX
