BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXX X XXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX  XXXXX  XXXX
            XXXXXX
            XXXXX
                XXX XXXXXXXXXX XXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                             XX XXXXXXXXXXXXXXXXXX
                        XXXX
                        XXX XXXXXXXXXXXXXXXXXXXXXX
                            BBB BBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
                                BB BBBBBBBBBBBBBB  BB BBBBBBBBBBBBBBBB
                                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFXX
                                        XXXXXXXXX
                                    XXX XXXXXXXXXXXXXXXXXXXXX
                                BBBBB
                            BBBBBB
                        XXXXX
                    XXXXX
                XXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXXX
        XXX XXXXXX X XXXXXXX  XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX X XX X XXX
            X XX X XXX X XX X XXX X XX X XXXX
        XXX XXXX X XXX XXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXX XXXXX XXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXX
        XXX XXXXXX X XXX XXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX X XXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX XXXXX XXX XXX XXXXXXX
        XX
    XXXXXXXXX
XXXXXXX
XXXXXXX
