kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: celery-redis
  name: celery-redis
  namespace: ops
spec:
  type: LoadBalancer
  ports:
    - port: 6379 
      targetPort: 6379
  selector:
    k8s-app: celery-redis
