# Generated by Django 2.1.4 on 2020-05-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=64, unique=True, verbose_name='组名称')),
                ('groupident', models.CharField(max_length=64, unique=True, verbose_name='组标识')),
            ],
            options={
                'verbose_name': '组标识',
                'verbose_name_plural': '组标识',
            },
        ),
    ]
